repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    name: Removing trailing whitespace
    exclude: '(README\.md|static|docs|VK-Overflow/static_dev/)'
  - id: end-of-file-fixer
    name: Checking EOF with newline
    exclude: '(README\.md|static|docs|VK-Overflow/static_dev/)'

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      name: Running flake8
      additional_dependencies: [
        'flake8-alphabetize==0.0.21',
        'flake8-import-order==0.19.2',
      ]

- repo: local
  hooks:
    - id: tests
      name: Running tests
      language: system
      verbose: false
      pass_filenames: false
      entry: python ./VK_Overflow/manage.py test VK_Overflow
      always_run: true
      # stages: [manual, push]
