services:
  centrifugo:
      container_name: centrifugo
      image: centrifugo/centrifugo:v6
      volumes:
        - ./centrifugo/:/centrifugo/
      command: centrifugo -c /centrifugo/config.json
      ports:
        - ${CENTRIFUGO_PORT:-8001}:8001
      ulimits:
        nofile:
          soft: 65535
          hard: 65535

  postgres:
    container_name: postgres
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  memcached:
    container_name: memcached
    image: memcached:1.6.39
    restart: unless-stopped
    ports:
      - ${MEMCACHED_PORT}:11211
    command: memcached -m 256
