# Generated by Django 5.2.7 on 2025-11-13 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_tag_answergrade_questiongrade_question_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('grey', 'grey'), ('blue', 'blue'), ('green', 'green'), ('cyan', 'cyan')], default='grey', max_length=32, verbose_name='Цвет тега'),
        ),
        migrations.AlterUniqueTogether(
            name='answergrade',
            unique_together={('author', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questiongrade',
            unique_together={('author', 'question')},
        ),
    ]
