# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
