# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations
from ..utils import recalculate_question_ratings


class Migration(migrations.Migration):
    dependencies = [
        ('questions', '0006_question_rating'),
    ]

    operations = [
        migrations.RunPython(recalculate_question_ratings),
    ]
