# Generated by Django 5.2.7 on 2025-11-21 10:15

from django.db import migrations
from ..utils import recalculate_answer_ratings


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_answer_rating'),
    ]

    operations = [
        migrations.RunPython(recalculate_answer_ratings),
    ]
