# Generated by Django 5.2.7 on 2025-12-14 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_recalculatung_answer_ratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answergrade',
            name='grade',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Задан пользователем'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='questions.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='questiongrade',
            name='grade',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], default=0, verbose_name='Оценка'),
        ),
    ]
