# Generated by Django 5.2.7 on 2025-12-19 12:02
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_answer_author_alter_answer_question_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
