# Generated by Django 5.2.7 on 2025-12-19 12:34

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_enable_postgres_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='trgm_idx_title', opclasses=['gin_trgm_ops']),
        ),
    ]
