# Generated by Django 5.2.7 on 2025-12-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_trgm_idx_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='best_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for', to='questions.answer', verbose_name='Лучший ответ'),
        ),
    ]
