# Generated by Django 5.2.7 on 2025-11-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.TextField(blank=True, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.TextField(blank=True, null=True, verbose_name='Telegram'),
        ),
    ]
