# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_github_alter_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(default='', max_length=64, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='', max_length=64, verbose_name='Telegram'),
        ),
    ]
